### ISSUE TITLE
What does AbChain_immunopeptide_regions_span mean?

### ISSUE THREAD

**Issue by chrisxu2016** [csi-greifflab/developability_profiling#1]
As the title shows, I don’t know how to calculate AbChain_immunopeptide_regions_span in your source code file [sequence_dp_calculations.R](https://github.com/csi-greifflab/developability_profiling/blob/main/scripts/developability/sequence_DPs/sequence_dp_calculations.R#L253). thank you very much for your suggestion

**Comment by jahnzh** [comment]
It is now added to calculations script.
